modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="alwaysallowtp"
version="${mod_version}"
displayName="${mod_name}"
description='''${mod_description}'''
authors="${mod_authors}"
logoFile="assets/alwaysallowtp/textures/icon.png"

[[dependencies.alwaysallowtp]]
modId="forge"
mandatory=true
versionRange="[47.4.13,)"
ordering="NONE"
side="BOTH"

[[dependencies.alwaysallowtp]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"